In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import pandas as pd
import glob
import numpy as np
import os

In [3]:
#old
old_numerator = pd.read_csv("MMR_Numerator_FY26Feb_Total_nlsn2(414).csv") # full deliverable

#new
new_numerator = pd.read_csv("FY26Mar_mmr_numerator_bq_nlsn2.csv")

In [4]:
old_numerator.head()

,fiscal_year,wm_year_nbr,wm_month_nbr,wm_month_desc,cal_year_nbr,cal_month_nbr,date,Business_Unit,Major_Business,Department,Category_Group,Category,mmr_hier_id,reporting_level,Channel,WM_Sales
0,FY 20,2019,1,February,2019,2,2019-02-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2414057.39
1,FY 20,2019,1,February,2019,2,2019-02-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Total,2414057.39
2,FY 20,2019,2,March,2019,3,2019-03-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2795375.35
3,FY 20,2019,2,March,2019,3,2019-03-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Total,2795375.35
4,FY 20,2019,3,April,2019,4,2019-04-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Total,2613121.54

In [5]:
new_numerator.tail()

,fiscal_year,wm_year_nbr,wm_month_nbr,wm_month_desc,cal_year_nbr,cal_month_nbr,date,Business_Unit,Major_Business,Department,Category_Group,Category,mmr_hier_id,reporting_level,Channel,WM_Sales
2765,FY 25,2024,12,January,2025,1,2025-01-01,FOOD,FRESH,MEAT AND SEAFOOD,PORK AND SAUSAGE,PORK AND SAUSAGE,MMR381400,CATEGORY_GROUP,Total,1.639622e+08
2766,FY 25,2024,12,January,2025,1,2025-01-01,FOOD,FRESH,PRODUCE,TRUCK VEGETABLES AND GREENS,TRUCK VEGETABLES AND GREENS,MMR473300,CATEGORY_GROUP,Total,1.400659e+08
2767,FY 25,2024,12,January,2025,1,2025-01-01,FOOD,FRESH,PRODUCE,TRUCK VEGETABLES AND GREENS,TRUCK VEGETABLES AND GREENS,MMR473300,CATEGORY_GROUP,Offline,1.400659e+08
2768,FY 25,2024,12,January,2025,1,2025-01-01,FOOD,FRESH,PRODUCE,BANANAS PINEAPPLES AND TROPICALS,BANANAS PINEAPPLES AND TROPICALS,MMR473000,CATEGORY_GROUP,Offline,1.117689e+08
2769,FY 25,2024,12,January,2025,1,2025-01-01,FOOD,FRESH,PRODUCE,BANANAS PINEAPPLES AND TROPICALS,BANANAS PINEAPPLES AND TROPICALS,MMR473000,CATEGORY_GROUP,Total,1.117689e+08

In [6]:
#old version
prev_mon = 'Feb' ## older numerator(v1)
#new version
curr_mon = 'Mar' ## new numerator (v2)

In [7]:
#check 1
date_check_1 = '202501'
#check 2
date_check_2 = '202502'

In [8]:
old_numerator['version'] = prev_mon
new_numerator['version'] = curr_mon

In [9]:
#concatenate calendar_year and calendar_month
#old
for index, row in old_numerator.iterrows():
    if len(str(old_numerator.loc[index,'cal_month_nbr']))==1:
        old_numerator.loc[index,'concat_date'] = str( old_numerator.loc[index,'cal_year_nbr'])+"0"+str( old_numerator.loc[index,'cal_month_nbr'])
    else:
        old_numerator.loc[index,'concat_date'] = str( old_numerator.loc[index,'cal_year_nbr'])+str( old_numerator.loc[index,'cal_month_nbr'])
#new
for index, row in new_numerator.iterrows():
    if len(str(new_numerator.loc[index,'cal_month_nbr']))==1:
        new_numerator.loc[index,'concat_date'] = str(new_numerator.loc[index,'cal_year_nbr'])+"0"+str(new_numerator.loc[index,'cal_month_nbr'])
    else:
        new_numerator.loc[index,'concat_date'] = str(new_numerator.loc[index,'cal_year_nbr'])+str(new_numerator.loc[index,'cal_month_nbr'])

In [10]:
#append old and new
#df = old_numerator.append(new_numerator)
df = pd.concat([old_numerator, new_numerator])

In [11]:
df.head()

,fiscal_year,wm_year_nbr,wm_month_nbr,wm_month_desc,cal_year_nbr,cal_month_nbr,date,Business_Unit,Major_Business,Department,Category_Group,Category,mmr_hier_id,reporting_level,Channel,WM_Sales,version,concat_date
0,FY 20,2019,1,February,2019,2,2019-02-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2414057.39,Feb,201902
1,FY 20,2019,1,February,2019,2,2019-02-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Total,2414057.39,Feb,201902
2,FY 20,2019,2,March,2019,3,2019-03-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2795375.35,Feb,201903
3,FY 20,2019,2,March,2019,3,2019-03-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Total,2795375.35,Feb,201903
4,FY 20,2019,3,April,2019,4,2019-04-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Total,2613121.54,Feb,201904

In [12]:
#check month
print(prev_mon," date",df[df['version']==prev_mon]['concat_date'].unique())
print(curr_mon, " date",df[df['version']==curr_mon]['concat_date'].unique())

Feb  date ['201902' '201903' '201904' '201905' '201906' '201907' '201908' '201909'
 '201910' '201911' '201912' '202001' '202002' '202003' '202004' '202005'
 '202006' '202007' '202008' '202009' '202010' '202011' '202012' '202101'
 '202102' '202103' '202104' '202105' '202106' '202107' '202108' '202109'
 '202110' '202111' '202112' '202201' '202202' '202203' '202204' '202205'
 '202206' '202207' '202208' '202209' '202210' '202211' '202212' '202301'
 '202302' '202303' '202304' '202305' '202306' '202307' '202308' '202309'
 '202310' '202311' '202312' '202401' '202402' '202403' '202404' '202405'
 '202406' '202407' '202408' '202409' '202410' '202411' '202412' '202501'
 '202502']
Mar  date ['202502' '202503' '202501']

### QC:  compare sales difference % and $ over period

In [14]:
#need attention if |$diff| > 5M or |diff%| > 1%
def highlight_red_or_green(val):
    color = 'red' if abs(val) >5000000 else 'green'
    return 'color: %s' % color

In [15]:
pip install Jinja2

Requirement already satisfied: Jinja2 in /opt/anaconda3/lib/python3.12/site-packages (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from Jinja2) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

#### Offline over periods

In [17]:
offline_QC_period = pd.pivot_table(df[df['Channel']=='Offline'], values='WM_Sales', index=['cal_year_nbr', 'cal_month_nbr'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
offline_QC_period.head()
#column name need to be changed
offline_QC_period["diff"] = offline_QC_period[curr_mon] - offline_QC_period[prev_mon]
offline_QC_period["diff%"] = (offline_QC_period[curr_mon] - offline_QC_period[prev_mon])/offline_QC_period[prev_mon]

offline_QC_period.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/615583702.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  offline_QC_period = pd.pivot_table(df[df['Channel']=='Offline'], values='WM_Sales', index=['cal_year_nbr', 'cal_month_nbr'],

In [18]:
offline_QC_period[['diff','diff%']].style.applymap(highlight_red_or_green)

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/1801181435.py:1: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  offline_QC_period[['diff','diff%']].style.applymap(highlight_red_or_green)

#### Online over periods

In [20]:
# df.head()?
df[(df['Channel']=='Online') & (df['version']=='April')].head()

df[(df['Channel']=='Online')].head()

,fiscal_year,wm_year_nbr,wm_month_nbr,wm_month_desc,cal_year_nbr,cal_month_nbr,date,Business_Unit,Major_Business,Department,Category_Group,Category,mmr_hier_id,reporting_level,Channel,WM_Sales,version,concat_date
0,FY 20,2019,1,February,2019,2,2019-02-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2414057.39,Feb,201902
2,FY 20,2019,2,March,2019,3,2019-03-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2795375.35,Feb,201903
5,FY 20,2019,3,April,2019,4,2019-04-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2613121.54,Feb,201904
6,FY 20,2019,4,May,2019,5,2019-05-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,2700932.36,Feb,201905
8,FY 20,2019,5,June,2019,6,2019-06-01,FOOD,FRESH,BAKERY,BAKERY - Online,BAKERY - Online,MMR040000,DEPARTMENT_TOTAL,Online,3547407.05,Feb,201906

In [21]:
#online_QC_period.head()

In [22]:
 offline_QC_period.head()

version                              Feb  Mar          diff  diff%
cal_year_nbr cal_month_nbr
2019         2              1.496840e+10  0.0 -1.496840e+10   -1.0
             3              1.887170e+10  0.0 -1.887170e+10   -1.0
             4              1.558810e+10  0.0 -1.558810e+10   -1.0
             5              1.515876e+10  0.0 -1.515876e+10   -1.0
             6              1.899013e+10  0.0 -1.899013e+10   -1.0

In [23]:
online_QC_period = pd.pivot_table(df[df['Channel']=='Online'], values='WM_Sales', index=['cal_year_nbr', 'cal_month_nbr'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)

#column name need to be changed
online_QC_period["diff"] = online_QC_period[curr_mon] - online_QC_period[prev_mon]
online_QC_period["diff%"] = (online_QC_period[curr_mon] - online_QC_period[prev_mon])/online_QC_period[prev_mon]

online_QC_period.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/3409381106.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  online_QC_period = pd.pivot_table(df[df['Channel']=='Online'], values='WM_Sales', index=['cal_year_nbr', 'cal_month_nbr'],

In [24]:
online_QC_period[['diff','diff%']].style.applymap(highlight_red_or_green)

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/607502942.py:1: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  online_QC_period[['diff','diff%']].style.applymap(highlight_red_or_green)

### QC:  compare sales difference % and $ by department for selected month

#### Offline, by department for selected month

In [27]:
offline_QC_department_1 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['Department'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
offline_QC_department_1["diff"] = offline_QC_department_1[curr_mon] - offline_QC_department_1[prev_mon]
offline_QC_department_1["diff%"] = (offline_QC_department_1[curr_mon] - offline_QC_department_1[prev_mon])/offline_QC_department_1[prev_mon]
offline_QC_department_1.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/4282660238.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  offline_QC_department_1 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['Department'],

#### Online, by department for selected month

In [29]:
online_QC_department_1 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['Department'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
online_QC_department_1["diff"] = online_QC_department_1[curr_mon] - online_QC_department_1[prev_mon]
online_QC_department_1["diff%"] = (online_QC_department_1[curr_mon] - online_QC_department_1[prev_mon])/online_QC_department_1[prev_mon]
online_QC_department_1.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/2001492741.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  online_QC_department_1 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['Department'],

### QC:  compare sales difference % and $ by MMRID for selected month

#### Offline, by MMRID for selected month

In [32]:
offline_QC_MMRID_1 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['mmr_hier_id'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
offline_QC_MMRID_1["diff"] = offline_QC_MMRID_1[curr_mon] - offline_QC_MMRID_1[prev_mon]
offline_QC_MMRID_1["diff%"] = ( offline_QC_MMRID_1[curr_mon] - offline_QC_MMRID_1[prev_mon])/offline_QC_MMRID_1[prev_mon]
offline_QC_MMRID_1.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/3917501211.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  offline_QC_MMRID_1 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['mmr_hier_id'],

In [33]:
offline_QC_MMRID_1.sort_values('diff')

version               Feb           Mar   diff         diff%
mmr_hier_id
MMR040100    7.676847e+07  7.676847e+07   0.00  0.000000e+00
MMR329999    1.154870e+06  1.154870e+06   0.00  0.000000e+00
MMR321303    8.273391e+06  8.273391e+06   0.00  0.000000e+00
MMR321302    1.544742e+07  1.544742e+07   0.00  0.000000e+00
MMR321301    6.176725e+06  6.176725e+06   0.00  0.000000e+00
...                   ...           ...    ...           ...
MMR231301    1.540346e+08  1.540347e+08   2.98  1.934630e-08
MMR421403    1.324081e+07  1.324082e+07  17.49  1.320917e-06
MMR421302    5.852855e+06  5.852881e+06  25.56  4.367099e-06
MMR431704    2.786113e+08  2.786113e+08  68.00  2.440677e-07
MMR243303    5.765375e+07  5.765384e+07  91.00  1.578388e-06

[438 rows x 4 columns]

#### Online, by MMRID for selected month

In [35]:
online_QC_MMRID_1 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['mmr_hier_id'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
online_QC_MMRID_1["diff"] = online_QC_MMRID_1[curr_mon] - online_QC_MMRID_1[prev_mon]
online_QC_MMRID_1["diff%"] = (online_QC_MMRID_1[curr_mon] - online_QC_MMRID_1[prev_mon])/online_QC_MMRID_1[prev_mon]
online_QC_MMRID_1.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/1701333011.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  online_QC_MMRID_1 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_1)], values='WM_Sales', index=['mmr_hier_id'],

### QC:  compare sales difference % and $ by department for 2nd selected month

#### Offline, by department for selected month

In [38]:
offline_QC_department_2 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['Department'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
offline_QC_department_2["diff"] = offline_QC_department_2[curr_mon] - offline_QC_department_2[prev_mon]
offline_QC_department_2["diff%"] = (offline_QC_department_2[curr_mon] - offline_QC_department_2[prev_mon])/offline_QC_department_2[prev_mon]
offline_QC_department_2.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/858570427.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  offline_QC_department_2 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['Department'],

#### Online, by department for selected month

In [40]:
online_QC_department_2 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['Department'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
online_QC_department_2["diff"] = online_QC_department_2[curr_mon] - online_QC_department_2[prev_mon]
online_QC_department_2["diff%"] = (online_QC_department_2[curr_mon] - online_QC_department_2[prev_mon])/online_QC_department_2[prev_mon]
online_QC_department_2.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/125281625.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  online_QC_department_2 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['Department'],

### QC:  compare sales difference % and $ by MMRID for selected month

#### Offline, by MMRID for selected month

In [43]:
offline_QC_MMRID_2 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['mmr_hier_id'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
offline_QC_MMRID_2["diff"] = offline_QC_MMRID_2[curr_mon] - offline_QC_MMRID_2[prev_mon]
offline_QC_MMRID_2["diff%"] = ( offline_QC_MMRID_2[curr_mon] - offline_QC_MMRID_2[prev_mon])/offline_QC_MMRID_2[prev_mon]
offline_QC_MMRID_2.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/3601507683.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  offline_QC_MMRID_2 = pd.pivot_table(df[(df['Channel']=='Offline')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['mmr_hier_id'],

#### Online, by MMRID for selected month

In [45]:
online_QC_MMRID_2 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['mmr_hier_id'],
                    columns=['version'], aggfunc=np.sum, fill_value=0)
online_QC_MMRID_2["diff"] = online_QC_MMRID_2[curr_mon] - online_QC_MMRID_2[prev_mon]
online_QC_MMRID_2["diff%"] = (online_QC_MMRID_2[curr_mon] - online_QC_MMRID_2[prev_mon])/online_QC_MMRID_2[prev_mon]
online_QC_MMRID_2.style.format({
    curr_mon: '{:,.2f}'.format,
    prev_mon: '{:,.2f}'.format,
    'diff': '{:,.2f}'.format,
    'diff%': '{:,.2%}'.format,
})

/var/folders/xk/pl3jmg716fl_105yxbpsvf7w0000gp/T/ipykernel_17997/1801157256.py:1: FutureWarning: The provided callable <function sum at 0x113ed7e20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  online_QC_MMRID_2 = pd.pivot_table(df[(df['Channel']=='Online')&df['concat_date'].str.contains(date_check_2)], values='WM_Sales', index=['mmr_hier_id'],

In [46]:
#set path to save files
# final_path = "/Users/y0h06pz/Library/CloudStorage/OneDrive-WalmartInc/Numerator/FY23DEC/"
# create a excel writer object
with pd.ExcelWriter("MMR_Numerator_FY26_Mar_tocheck_nlsn0417.xlsx") as writer:
    # use to_excel function and specify the sheet_name and index
    # to store the dataframe in specified sheet
    df.to_excel(writer, sheet_name="Flat", index=False)
    offline_QC_period.to_excel(writer, sheet_name="QC_over_period_Offline", index=True)
    online_QC_period.to_excel(writer, sheet_name="QC_over_period_Online", index=True)
    online_QC_department_1.to_excel(writer, sheet_name="QC_by_department_Online_"+str(date_check_1), index=True)
    offline_QC_department_1.to_excel(writer, sheet_name="QC_by_department_Offline_"+str(date_check_1), index=True)
    offline_QC_MMRID_1.to_excel(writer, sheet_name="QC_by_MMRID_Offline_"+str(date_check_1), index=True)
    online_QC_MMRID_1.to_excel(writer, sheet_name="QC_by_MMRID_Online_"+str(date_check_1), index=True)
    online_QC_department_2.to_excel(writer, sheet_name="QC_by_department_Online_"+str(date_check_2), index=True)
    offline_QC_department_2.to_excel(writer, sheet_name="QC_by_department_Offline_"+str(date_check_2), index=True)
    offline_QC_MMRID_2.to_excel(writer, sheet_name="QC_by_MMRID_Offline_"+str(date_check_2), index=True)
    online_QC_MMRID_2.to_excel(writer, sheet_name="QC_by_MMRID_Online_"+str(date_check_2), index=True)